'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34014
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")>  _
Partial Friend NotInheritable Class modelSetting
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As modelSetting = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New modelSetting()),modelSetting)
    
    Public Shared ReadOnly Property [Default]() As modelSetting
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Data Source=.\SQLExpress;Initial Catalog=clinica;User ID=sa;Password=jnl0pes*")>  _
    Public ReadOnly Property SQLServerString() As String
        Get
            Return CType(Me("SQLServerString"),String)
        End Get
    End Property
End Class
